<<<<<<< HEAD
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

=======
INC_DIR 	= include
KER_DIR		= kernel
SRC_DIR		= main
NVCC        = nvcc
NVCC_FLAGS  = -O3 -I/usr/local/cuda/include -I$(INC_DIR) -I$(KER_DIR)
LD_FLAGS    = -lcudart -L/usr/local/cuda/lib64
EXE1	    = scene1
OBJ1        = scene1.o 
EXE2	    = scene2
OBJ2        = scene2.o 
EXE3	    = scene3
OBJ3        = scene3.o 

all: scene1 scene2 scene3

$(EXE1): $(OBJ1)
	$(NVCC) $(OBJ1) -o $(EXE1) 

$(EXE2): $(OBJ2)
	$(NVCC) $(OBJ2) -o $(EXE2) 

$(EXE3): $(OBJ3)
	$(NVCC) $(OBJ3) -o $(EXE3)


$(OBJ1): $(SRC_DIR)/scene1.cu $(KER_DIR)/kernel.h
	$(NVCC) -c -o $@ $(SRC_DIR)/scene1.cu $(NVCC_FLAGS)

$(OBJ2): $(SRC_DIR)/scene2.cu $(KER_DIR)/kernel.h
	$(NVCC) -c -o $@ $(SRC_DIR)/scene2.cu $(NVCC_FLAGS)

$(OBJ3): $(SRC_DIR)/scene3.cu $(KER_DIR)/kernel.h
	$(NVCC) -c -o $@ $(SRC_DIR)/scene3.cu $(NVCC_FLAGS)
>>>>>>> cuda

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zengdekang/Github/CS217-RayTracing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zengdekang/Github/CS217-RayTracing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zengdekang/Github/CS217-RayTracing/CMakeFiles /Users/zengdekang/Github/CS217-RayTracing/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zengdekang/Github/CS217-RayTracing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
<<<<<<< HEAD
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TestRT

# Build rule for target.
TestRT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestRT
.PHONY : TestRT

# fast build rule for target.
TestRT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRT.dir/build.make CMakeFiles/TestRT.dir/build
.PHONY : TestRT/fast

#=============================================================================
# Target rules for targets named RayTracing

# Build rule for target.
RayTracing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RayTracing
.PHONY : RayTracing

# fast build rule for target.
RayTracing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracing.dir/build.make CMakeFiles/RayTracing.dir/build
.PHONY : RayTracing/fast

main/main.o: main/main.cpp.o

.PHONY : main/main.o

# target to build an object file
main/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracing.dir/build.make CMakeFiles/RayTracing.dir/main/main.cpp.o
.PHONY : main/main.cpp.o

main/main.i: main/main.cpp.i

.PHONY : main/main.i

# target to preprocess a source file
main/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracing.dir/build.make CMakeFiles/RayTracing.dir/main/main.cpp.i
.PHONY : main/main.cpp.i

main/main.s: main/main.cpp.s

.PHONY : main/main.s

# target to generate assembly for a file
main/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RayTracing.dir/build.make CMakeFiles/RayTracing.dir/main/main.cpp.s
.PHONY : main/main.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRT.dir/build.make CMakeFiles/TestRT.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRT.dir/build.make CMakeFiles/TestRT.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestRT.dir/build.make CMakeFiles/TestRT.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RayTracing"
	@echo "... TestRT"
	@echo "... main/main.o"
	@echo "... main/main.i"
	@echo "... main/main.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

=======
	rm -rf *.o $(EXE1) $(EXE2) $(EXE3)
	rm -rf result/*
>>>>>>> cuda
